### PR TITLE
Bridge Binance 

### PR DESCRIPTION
**Pull request by Camisul**

### CODE REVIEW

**Comment by geohot** [comment]
Looking good! Let me know when it's ready

**Comment by Camisul** [comment]
Should be good to go

**Comment by geohot** [comment]
Yea, it looks to me like the whole validator set was in there, so it shouldn't be too hard.

**Comment by Camisul** [comment]
I think that's it

**Comment by geohot** [comment]
Great stuff! Should have time on Friday to finish the cTH wrapper bridge and deploy this.

**Comment by geohot** [comment]
You figure out why you need the +27s?

**Comment by Camisul** [comment]
It's specified in eth yellow paper, appendix F. I saw some open issues about inconsistent behavior of `web3.eth.sign` in ganache trufflesuite/ganache-cli#757 and figured bsc does the same.

**Pull request merged**
